config/routes.rb
Csc::Application.routes.draw do
  resources :shortmessages do
    get :export, :on=>:collection
  end

  resources :universities

  resources :deducations do
    get :payment_mode, :on=>:collection
    get :get_amount, :on=>:collection
    get :update_status, :on=>:member
    get :print, :on=>:member
  end

  resources :courses

  resources :downloads

  resources :bulkmails do
    get :mail_mode, :on=>:collection
  end

  resources :deposits do
    get :transaction_mode, :on=>:collection
    get :update_status, :on=>:member
    get :update_funds, :on=>:member
    get :upload_funds, :on=>:collection
    get :upload, :on=>:member
    put :fund_save, :on=>:collection
    get :suspense_transactions, :on=>:collection
  end

  resources :pancards do
    get :update_status, :on=>:member
    get :payment_mode, :on=>:collection
    get :print, :on=>:member
    get :suspense_transactions, :on=>:collection
  end

  resources :tickets

  resources :policynames

  resources :insurances do
    get 'export', :on=>:collection
    get 'print', :on=>:member
    get 'receipt', :on=>:member
    get 'courier', :on=>:member
    post 'courier_update', :on=>:member
    get 'verifyinsurance', :on=>:collection
    get 'update_status', :on=>:member
    get 'verifiedinsurance', :on=>:collection
    get 'renewpolicy', :on=>:collection
    put 'createrenew', :on=>:collection
    get :eodreport, :on=>:collection
    get :daterangereport, :on=>:collection
    get :eodexport, :on=>:collection
    get :daterangeexport, :on=>:collection
    get :payment_mode, :on=>:collection
    get :suspense_transactions, :on=>:collection
  end

  resources :user_profiles

  resources :blocks do
    get 'load_districts', :on => :collection
    get :export, :on=>:collection
  end

  resources :divisions do
    get :export, :on=>:collection
  end

  resources :districts do
    get :export, :on => :collection
  end

  resources :states do
    get :export, :on=>:collection
  end

  resources :users do
    get 'verifyuser', :on=>:collection
    get 'update_status', :on=>:member
    get 'profile', :on=>:member
    get 'document', :on=>:member
    put 'upload_document', :on=>:member
    get 'editprofile', :on=>:member
    put 'updateprofile', :on=>:member
    get 'upload', :on=>:collection
    post 'csv_import', :on=>:collection
    get 'changepassword', :on=>:member
    get :resetpass, :on=>:member
    get :payment_mode, :on=>:collection
    get :activity, :on=>:member
    get :export, :on=>:collection
  end

  resources :roles

  resources :user_sessions

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"

  match "user_info/:id" => "user_info#index", :as=>:user_info
  get "user_info/index"


  match ':controller(/:action(/:id(.:format)))'
end

app/models/pancard.rb
class Pancard < ActiveRecord::Base
  #Relations
  belongs_to :district
  belongs_to :state
  belongs_to :user
  
  #search using meta_where Gem
  def self.search(search)
    if search
      where(:panapplication_number.matches => "%#{search}%")
    else
      scoped
    end
  end
  
  #Upload Documents
  has_attached_file :idproof, :styles => { :medium => "300x300>",  :small=>"50x50" }
  has_attached_file :addressproof, :styles => { :medium => "300x300>",:small=>"50x50" }
  has_attached_file :dobproof, :styles => { :medium => "300x300>",  :small=>"50x50" }

end

app/controllers/pancards_controller.rb
#Author:Chaitanya Ram
#=========================================
class PancardsController < ApplicationController
  layout "admin"
  before_filter :require_user, :recent_items
  filter_access_to :all
  helper_method :sort_column, :sort_direction
######## For SMS Gateway ##############
  require 'net/http'
  require 'uri'
####################################
  def index
    @pancards = Pancard.where(:created_by=>current_user.id,:suspense_status => false).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page, :per_page=>per_page) if has_role?(:vle)
    @pancards = Pancard.where(:suspense_status => false).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page, :per_page=>per_page) if has_role?(:admin) or has_role?(:manager)
    @pancards = Pancard.joins({:user=>:user_profile}).where({:user=>{:user_profile=>{:district_id=>current_user.user_profile.district_id}}},:suspense_status=>false).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page, :per_page=>per_page) if has_role?(:district_manager) or has_role?(:district_engineer)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @pancards }
      format.js
    end
  end

  def show
    @pancard = Pancard.find(params[:id])
    render :layout => "application"
  end

  def new
    @pancard = Pancard.new
    render :layout => "application"
  end

  def edit
    @pancard = Pancard.find(params[:id])
    render :layout => "application"
  end

  def create
    @pancard = Pancard.new(params[:pancard])
    @pancard.created_by = @pancard.user_id = current_user.id
    @pancard.panapplication_number = 'PAN/' + current_user.id.to_s + '/' + Time.now.strftime('%y%m%d%H%M%S').to_s
    @pancard.dob = params[:dob]
    @user_profile_user = UserProfile.find(:first, :conditions=>{:user_id=>current_user.id})
    user_profile_user_funds = @user_profile_user.available_funds

    if user_profile_user_funds <=0
      flash[:error] = "Sorry! You have No Funds to perform Transaction."
      redirect_to(insurances_url)
    else
      user_profile_remaining_funds = user_profile_user_funds - params[:pancard][:amount].to_f #transaction_records_sum

      if user_profile_remaining_funds < 0
        flash[:error] = "Sorry! You have Insufficient Funds.Transaction is Cancelled."
        redirect_to(insurances_url)
      else
        respond_to do |format|
          if @pancard.save
            @pancard_transaction = Transaction.new(:user_id=>current_user.id, :transaction_number=>@pancard.panapplication_number, :transaction_date=>Date.today, :transaction_mode=>'Dr', :service=>"PAN", :amount=>params[:pancard][:amount])
            @pancard_transaction.save
            @user_profile_user.available_funds = user_profile_remaining_funds
            @user_profile_user.save

            sms_status ### Send SMS

            format.html { redirect_to(@pancard, :notice => 'PAN Application was successfully Created.') }
            format.xml { render :xml => @pancard, :status => :created, :location => @pancard }
          else
            format.html { render :action => "new" }
            format.xml { render :xml => @pancard.errors, :status => :unprocessable_entity }
          end
        end
      end
    end
  end

  def update
    @pancard = Pancard.find(params[:id])

    respond_to do |format|
      if @pancard.update_attributes(params[:pancard])
        format.html { redirect_to(@pancard, :notice => 'PAN Application was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @pancard.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @pancard = Pancard.find(params[:id])
    @pancard.destroy

    respond_to do |format|
      format.html { redirect_to(pancards_url) }
      format.xml { head :ok }
    end
  end

  def update_status
    pancard = Pancard.find(params[:id])
    pancard.update_attribute('status', pancard.status ? false : true)
    flash[:success] = "PAN Application Status has been updated."
    respond_to do |format|
      format.html { redirect_to(:controller=>'pancards', :action=>'index') }
    end
  end

  def payment_mode
    respond_to do |format|
      format.js
    end
  end

  def print
    @pancard = Pancard.find(params[:id])

    #qrcode content
    puts @qrcode = @pancard.panapplication_number + ',' + @pancard.transaction_date.strftime('%d-%m-%y') + ',' + @pancard.amount.to_s+ ',' + UserProfile.find_by_user_id(@pancard.user_id).vle_code + ',' + UserProfile.find_by_user_id(@pancard.user_id).panchayat + '/' + UserProfile.find_by_user_id(@pancard.user_id).district.name + ',' + UserProfile.find_by_user_id(@pancard.user_id).district_id.to_s + UserProfile.find_by_user_id(@pancard.user_id).state_id.to_s + @pancard.user_id.to_s + UserProfile.find_by_user_id(@pancard.user_id).id.to_s

    #PDF Render
    html = render_to_string :layout => false
    kit = PDFKit.new(html)
    kit.stylesheets << RAILS_ROOT + '/public/stylesheets/styles.css'
    send_data(kit.to_pdf, :filename => "PAN Receipt-#{@pancard.panapplication_number}.pdf", :type => 'application/pdf')
  end

  def sms_status
    mobile = @pancard.mobile
    message = "Dear Customer,Received amount of Rs."+@pancard.amount.to_s+"/- towards PAN Application.Your Reference No: "+@pancard.panapplication_number+"."
    url = "http://voice.full2ads.co.cc/api/sms.php?uid=6368616974616e7961&pin=4e4ce8b0a500c&sender=SARKCSC&route=1&mobile=#{mobile},9934186169&message=#{message}"
    Net::HTTP.get_print URI.parse(URI.encode(url.strip))

    @pancard_sms = Shortmessage.new(:user_id=>current_user.id, :transaction_id=>@pancard.panapplication_number, :service=>'PAN', :message=>message, :mobile=>mobile)
    @pancard_sms.save
  end

  def suspense
    pancard = Pancard.find(params[:id])
    pancard.update_attribute('suspense_status', pancard.suspense_status ? false : true)
    if pancard.suspense_status?
      flash[:success] = "PAN Card Transaction is Suspended."
      respond_to do |format|
        format.html { redirect_to(:controller=>'pancards', :action=>'index') }
      end
    else
      flash[:success] = "PAN Card Transaction is Reverted successfully"
      respond_to do |format|
        format.html { redirect_to(:controller=>'pancards', :action=>'suspense_transactions') }
      end
    end
  end

  def suspense_transactions
    @pancards = Pancard.where(:created_by=>current_user.id,:suspense_status => true).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page, :per_page=>per_page) if has_role?(:vle)
    @pancards = Pancard.where(:suspense_status => true).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page, :per_page=>per_page) if has_role?(:admin) or has_role?(:manager)
    @pancards = Pancard.joins({:user=>:user_profile}).where({:user=>{:user_profile=>{:district_id=>current_user.user_profile.district_id}}},:suspense_status=>true).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page, :per_page=>per_page) if has_role?(:district_manager) or has_role?(:district_engineer)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @pancards }
    end
  end

########################################  Private Methods #######################################################
  private
  def recent_items
    @recent_pancards = Pancard.where(:created_by=>current_user.id).order('created_at DESC').limit(5) if has_role?(:vle)
    @recent_pancards = Pancard.order('created_at DESC').limit(5) if has_role?(:admin)
    @recent_pancards = Pancard.order('created_at DESC').limit(5) if has_role?(:manager)
    @recent_pancards = Pancard.joins({:user=>:user_profile}).where({:user=>{:user_profile=>{:district_id=>current_user.user_profile.district_id}}}).order('pancards.created_at DESC').limit(5) if has_role?(:district_manager) or has_role?(:district_engineer)
  end

  def sort_column
    Pancard.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
######################################### Private Methods ############################################################
end

app/helpers/pancards_helper.rb
module PancardsHelper
end

app/views/pancards/_mode.html.erb
        <div>
            <label for="name">
               Bank Name (बैंक का नाम):<em>*</em>
            </label>
            &nbsp;&nbsp;&nbsp;<%= text_field_tag 'pancard[bank_name]','', :id=>"bankname", :onChange=>"capitalizeMe(this)",:class => "tipTip", :title=>"Name of the Bank. Ex: State Bank of India <br/>बैंक का नाम दर्ज करें.उदाहरण: एसबीआई", :size=>20 %>
           <script type="text/javascript">
                var bankname = new LiveValidation('bankname', {
                    onlyOnSubmit: true
                });
                bankname.add(Validate.Presence)
            </script>
        </div>

        <div>
            <label for="name">
              Branch (शाखा): <em>*</em>
            </label>
            &nbsp;&nbsp;&nbsp;<%= text_field_tag 'pancard[branch]','', :id=>"bbranch", :onChange=>"capitalizeMe(this)",:class => "tipTip", :title=>"Name of the Branch. Ex:Patna <br/>शाखा का नाम दर्ज करें. उदाहरण: पटना", :size=>20 %>
			          <script type="text/javascript">
                var bbranch = new LiveValidation('bbranch', {
                    onlyOnSubmit: true
                });
                bbranch.add(Validate.Presence)
            </script>
        </div>
        <div>
            <label for="name">
                DD/Cheque Number (डीडी / चेक संख्या):<em>*</em>
            </label>
            &nbsp;&nbsp;&nbsp;<%= text_field_tag 'pancard[instrument_number]','', :id=>"inumber", :class => "tipTip",  :title=>"Cheque/DD Number. Ex:123456<br/>चैक / डीडी संख्या.उदाहरण: 123456", :size=>20%>
          <script type="text/javascript">
                var inumber = new LiveValidation('inumber');
                inumber.add(Validate.Presence);
                inumber.add(Validate.Numericality, {
                    onlyInteger: true
                });
            </script>
        </div>
<div>
  <label for="name">
    Date (तारीख):<em>*</em>
  </label>
  &nbsp;&nbsp;&nbsp;<%= text_field_tag 'pancard[instrument_date]', Time.now.strftime('%d-%m-%Y'), :id=>"idate", :class => "formTextBox" %>

</div>

     <script>
	          $(function() {
		          $( "#idate" ).datepicker({dateFormat:'dd-mm-yy', maxDate:'+1m',changeMonth: true,changeYear: true,minDate:'-1m',currentText: 'Now' });
	          });
      	</script>

app/views/pancards/_pancards.html.erb
<div class="list">
  <table width="100%">
    <tr>
      <td align="right">
        <b>
          <i>per page</i>
        </b>
        <%= per_page %> | <%= page_entries_info @pancards, :entry_name => 'Application' %>
      </td>
    </tr>
  </table>
  <table class="tablesorter" cellspacing="1">
    <thead>
    <tr>
      <th>SNo</th>
      <th>Status</th>
      <th class="header"><%= sortable 'application number' %></th>
      <th>Transaction Date</th>
      <th>Name</th>
      <th>Amount</th>
      <% if has_role? (:vle) %>
      <% else %>
          <th>VLE ID</th>
          <th>VLE Name</th>
      <% end %>
      <th>Actions</th>
    </tr>
    </thead>
    <% i=1 %>
    <% @pancards.each do |pancard| %>
        <tr>
          <td><%= i %></td>
          <td>
            <% if pancard.status == false %>
                <font color='red'><b>P</b></font>
            <% else %>
                <font color='green'><b>A</b></font>
            <% end %>
          </td>
          <td><%= highlight(pancard.panapplication_number, params[:search]) %></td>
          <td><%= pancard.transaction_date.strftime("%d-%m-%Y") %></td>
          <td align="left"><%= pancard.first_name %> <%= pancard.middle_name %> <%= pancard.last_name %></td>
          <td align="right">&#x20B9; <%= pancard.amount.to_f %></td>
          <% if has_role? (:vle) %>
          <% else %>
              <td>
                <%= UserProfile.find_by_user_id(pancard.user_id).vle_code %>
              </td>
              <td align="left">
                <%= User.find_by_id(pancard.user_id).name %>
              </td>
          <% end %>
          <td><%= link_to 'View', pancard, :class=>"tipTip2", :title => "View Transaction" %>

            <% if has_role? (:vle) %>
                <%= link_to '| Receipt', {:action=>"print", :id=>pancard}, :class=>"tipTip2", :title => "Print Receipt" %>
            <% end %>
            <% if has_role?(:manager) %>
                |
                <%= link_to(pancard.status? ? 'Block' : 'Approve', {:action=>'update_status', :id=>pancard}, :class=>"tipTip2", :title => "Approve (or) Block Transaction") %>
            <% end %>
        </tr>
        <% i = i + 1 %>
    <% end %>
  </table>
  <div class="flickr_pagination">
  <%= page_entries_info @pancards, :entry_name => 'PAN Application' %>  <%= will_paginate @pancards, :container => false %>
  </div>
</div>

app/views/pancards/_recent_items.html.erb
<% for pancard in @recent_pancards %>
    <li class="" id="recent_pancard_<%= pancard.id %>">
      <dt>
        <%= link_to truncate(pancard.panapplication_number, :length=>27), pancard_path(pancard), :class=>"tipTip1", :title=>"View Transaction" %>
      </dt>
      <tt>
        <br/>
      </tt>
    </li>
<% end %>

app/views/pancards/edit.html.erb
<h3>PAN | Edit PAN Applicaiton</h3>

<%= render 'form' %>

<%= link_to 'Show', @pancard, :class=>"more" %> &nbsp;
<%= link_to 'Back', pancards_path, :class=>"more" %>

app/views/pancards/index.html.erb
<h3>PAN | Manage PAN Applications</h3>
<% if has_role?(:vle) %>
    <%= link_to 'New PAN Application', new_pancard_path, :class=>'more tipTip1', :title => "Create New PAN Application" %>
    <%= render :partial=>'common/funds' %>
    <br/><br/>
<% end %>
<div class="help_text">
  * List of All PAN Applications.<br/>
  * <b>Status</b>: <font color="red"><b>P</b></font> - Transaction is not
  yet approved by Manager and
  <font color="green"><b>A</b></font>-Approved by the Manager.
</div>

<div class="list">
  <table width="100%">
    <tr>
      <td align="right">
        <b>
          <i>per page</i>
        </b>
        <%= per_page %> | <%= page_entries_info @pancards, :entry_name => 'Application' %>
      </td>
    </tr>
  </table>
  <table class="tablesorter" cellspacing="1">
    <thead>
    <tr>
      <th>SNo</th>
      <th>Status</th>
      <th class="header"><%= sortable 'application number' %></th>
      <th>Transaction Date</th>
      <th>Name</th>
      <th>Amount (<span class="WebRupee">Rs</span>)</th>
      <% if has_role? (:vle) %>
      <% else %>
          <th>VLE ID</th>
          <th>VLE Name</th>
      <% end %>
      <th>Actions</th>
    </tr>
    </thead>
    <% i=1 %>
    <% @pancards.each do |pancard| %>
        <tr>
          <td><%= i %></td>
          <td>
            <% if pancard.status == false %>
                <font color='red'><b>P</b></font>
            <% else %>
                <font color='green'><b>A</b></font>
            <% end %>
          </td>
          <td><%= highlight(pancard.panapplication_number, params[:search]) %></td>
          <td><%= pancard.transaction_date.strftime("%d-%m-%Y") %></td>
          <td align="left"><%= pancard.first_name.titleize %> <%= pancard.middle_name.titleize %> <%= pancard.last_name.titleize %></td>
          <td align="right"><%= number_with_precision(pancard.amount, :precision=>2) %></td>
          <% if has_role? (:vle) %>
          <% else %>
              <td>
                <%= UserProfile.find_by_user_id(pancard.user_id).vle_code %>
              </td>
              <td align="left">
                <%= User.find_by_id(pancard.user_id).name %>
              </td>
          <% end %>
          <td><%= link_to 'View', pancard, :class=>"tipTip2", :title => "View Transaction" %>

            <% if has_role? (:vle) %>
                <%= link_to '| Receipt', {:action=>"print", :id=>pancard}, :class=>"tipTip2", :title => "Print Receipt" %>
            <% end %>
            <% if has_role?(:manager) %>
                |
                <%= link_to(pancard.status? ? 'Block' : 'Approve', {:action=>'update_status', :id=>pancard}, :class=>"tipTip2", :title => "Approve (or) Block Transaction") %>
                | <%= link_to "Suspend", {:action=>'suspense', :id=>pancard}, :class=>"tipTip2", :title => "Suspend Transaction" %>

            <% end %>
        </tr>
        <% i = i + 1 %>
    <% end %>
  </table>
  <div class="flickr_pagination">
  <%= page_entries_info @pancards, :entry_name => 'PAN Application' %>  <%= will_paginate @pancards, :container => false %>
  </div>
</div>

app/views/pancards/index.js.erb
$("#pancards").html("<%= escape_javascript(render 'pancards' ) %>");

app/views/pancards/new.html.erb
<h3>PAN | New PAN Application (पैन |नई पैन आवेदन )</h3>
<%= render :partial=>'common/funds' %>
<br/><br/>
<div class="list">
  <div class="help_text">
    * Fill the below form for PAN Application.(पैन आवेदन के लिए नीचे दिए फॉर्म भरें)<br/>
    * Please check all entries before Save.(सहेजें से पहले सभी प्रविष्टियों की जँच करें)
    <br/>*<font color="blue"> FURTHER MODIFICATION WILL NOT POSSIBLE AFTER SUBMITTING THE FORM (फार्म जमा करने के बाद
    आगे कोई संशोधन संभव नहीं होगा).</font>
  </div>
  <%= render 'form' %>
  <%= link_to 'Back to PAN Applications', pancards_path, :class=>'more tipTip1', :title => "Back to PAN Applications" %>
</div>

app/views/pancards/payment_mode.js.erb
<% if params[:name].eql?('Cash')%>
$('#transaction_fields').html("");
<% else %>
$('#transaction_fields').html("<%=escape_javascript(render 'mode')%>");
<% end %>

app/views/pancards/show.html.erb
<h3>PAN | View PAN Application Details</h3>

<% unless has_role? (:vle) %>
<% else %>
    <div class="list">
    <%= render :partial=>'common/funds' %>
    </div>
<% end %>
<div class="formbox">
  <div class="desc">PAN Application No : <%= @pancard.panapplication_number %></div>
  <div class="divider"></div>
  <div class="desc">Nameof the Applicant
    : <%= @pancard.first_name %>&nbsp;<%= @pancard.middle_name %>&nbsp;<%= @pancard.last_name %></div>
  <div class="divider"></div>
  <div class="desc">Father Name : <%= @pancard.father_name %></div>
  <div class="divider"></div>
  <div class="desc">DOB : <%= @pancard.dob.strftime('%d-%b-%Y') %></div>
  <div class="divider"></div>
  <div class="desc">Gender : <%= @pancard.gender %></div>
  <div class="divider"></div>
  <div class="desc">Address : <%= @pancard.address1 %>,<%= @pancard.address2 %>
    ,<%= @pancard.address2 %></div>
  <div class="divider"></div>
  <div class="desc">PIN : <%= @pancard.pincode %></div>
  <div class="divider"></div>
  <div class="desc">Village/Town Name : <%= @pancard.place %></div>
  <div class="divider"></div>
  <div class="desc">Mobile : <%= @pancard.mobile %></div>
  <div class="divider"></div>
  <div class="desc">Telephone : <%= @pancard.telephone %></div>
  <div class="divider"></div>
  <div class="desc">District : <%= @pancard.district.name %></div>
  <div class="divider"></div>
  <div class="desc">State : <%= @pancard.state.name %></div>
  <div class="divider"></div>
  <div class="desc">Amount : &#x20B9;. <%= @pancard.amount %></div>
  <div class="divider"></div>
  <div class="desc">Payment Mode : <%= @pancard.payment_mode %></div>
  <div class="divider"></div>
  <% if @pancard.payment_mode == 'Cash' %>
  <% else %>
      <div class="desc">DD/Cheque : <%= @pancard.instrument_number %></div>
      <div class="divider"></div>
      <div class="desc">Bank : <%= @pancard.bank_name %></div>
      <div class="divider"></div>
      <div class="desc">Branch : <%= @pancard.branch %></div>
      <div class="divider"></div>
      <div class="desc">Date : <%= @pancard.instrument_date.strftime('%d-%b-%Y') %></div>
      <div class="divider"></div>
  <% end %>
  <div class="desc">Documents :
    <table class="tablesorter" cellspacing="1">
      <thead>
      <tr>
        <th>
          ID Proof
        </th>
        <th>
          Address Proof
        </th>
        <th>
          DOB Proof
        </th>
      </tr>
      </thead>
      <tr>
        <td>
          <% if @pancard.idproof.file? %>
              <a href="<%= @pancard.idproof.url %>" rel="facebox"><%= image_tag @pancard.idproof.url(:small) %></a>
          <% else %>
              <%= image_tag "nophoto.jpg" %>
          <% end %>
        </td>
        <td>
          <% if @pancard.addressproof.file? %>
              <a href="<%= @pancard.addressproof.url %>" rel="facebox"><%= image_tag @pancard.addressproof.url(:small) %></a>
          <% else %>
              <%= image_tag "nophoto.jpg" %>
          <% end %>
        </td>
        <td>
          <% if @pancard.dobproof.file? %>
              <a href="<%= @pancard.dobproof.url %>" rel="facebox"><%= image_tag @pancard.dobproof.url(:small) %></a>
          <% else %>
              <%= image_tag "nophoto.jpg" %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <div class="divider"></div>
  <div class="desc">VLE ID
    :  <%= UserProfile.find_by_user_id(@pancard.user_id).vle_code %> </div>
  <div class="divider"></div>
  <div class="desc">VLE Name
    :  <%= User.find_by_id(@pancard.user_id).name %> </div>
  <div class="divider"></div>
</div>
<!-- <%= link_to 'Edit', edit_pancard_path(@pancard) %> | -->
  <div class="bottom_links">
    <%= link_to 'Back to PAN Applications', pancards_path, :class=>'more tipTip1', :title => "Back to PAN Applications" %>
  </div>