config/routes.rb
Csc::Application.routes.draw do
  resources :shortmessages do
    get :export, :on=>:collection
  end

  resources :universities

  resources :deducations do
    get :payment_mode, :on=>:collection
    get :get_amount, :on=>:collection
    get :update_status, :on=>:member
    get :print, :on=>:member
  end

  resources :courses

  resources :downloads

  resources :bulkmails do
    get :mail_mode, :on=>:collection
  end

  resources :deposits do
    get :transaction_mode, :on=>:collection
    get :update_status, :on=>:member
    get :update_funds, :on=>:member
    get :upload_funds, :on=>:collection
    get :upload, :on=>:member
    put :fund_save, :on=>:collection
    get :suspense_transactions, :on=>:collection
  end

  resources :pancards do
    get :update_status, :on=>:member
    get :payment_mode, :on=>:collection
    get :print, :on=>:member
    get :suspense_transactions, :on=>:collection
  end

  resources :tickets

  resources :policynames

  resources :insurances do
    get 'export', :on=>:collection
    get 'print', :on=>:member
    get 'receipt', :on=>:member
    get 'courier', :on=>:member
    post 'courier_update', :on=>:member
    get 'verifyinsurance', :on=>:collection
    get 'update_status', :on=>:member
    get 'verifiedinsurance', :on=>:collection
    get 'renewpolicy', :on=>:collection
    put 'createrenew', :on=>:collection
    get :eodreport, :on=>:collection
    get :daterangereport, :on=>:collection
    get :eodexport, :on=>:collection
    get :daterangeexport, :on=>:collection
    get :payment_mode, :on=>:collection
    get :suspense_transactions, :on=>:collection
  end

  resources :user_profiles

  resources :blocks do
    get 'load_districts', :on => :collection
    get :export, :on=>:collection
  end

  resources :divisions do
    get :export, :on=>:collection
  end

  resources :districts do
    get :export, :on => :collection
  end

  resources :states do
    get :export, :on=>:collection
  end

  resources :users do
    get 'verifyuser', :on=>:collection
    get 'update_status', :on=>:member
    get 'profile', :on=>:member
    get 'document', :on=>:member
    put 'upload_document', :on=>:member
    get 'editprofile', :on=>:member
    put 'updateprofile', :on=>:member
    get 'upload', :on=>:collection
    post 'csv_import', :on=>:collection
    get 'changepassword', :on=>:member
    get :resetpass, :on=>:member
    get :payment_mode, :on=>:collection
    get :activity, :on=>:member
    get :export, :on=>:collection
  end

  resources :roles

  resources :user_sessions

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"

  match "user_info/:id" => "user_info#index", :as=>:user_info
  get "user_info/index"


  match ':controller(/:action(/:id(.:format)))'
end

app/models/policyname.rb
#Author: Chaitanya
#Date: June 03 2011
#==============================
class Policyname < ActiveRecord::Base
  #Relations
  
  
  #Validations
  validates :name, :presence => true, :uniqueness => true, :length => { :maximum => 100}
  #search using meta_where Gem
  def self.search(search)
    if search
      where(:name.matches => "%#{search}%")
    else
      scoped
    end
  end

end

app/controllers/policynames_controller.rb
class PolicynamesController < ApplicationController
  layout "admin" 
  before_filter :require_user,:recent_items
  filter_access_to :all
  helper_method :sort_column, :sort_direction
  def index
    @policynames = Policyname.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page,:per_page=>per_page )
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @policynames }
      format.js
    end
  end
  
  def show
    @policyname = Policyname.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @policyname }
    end
  end
  
  def new
    @policyname = Policyname.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @policyname }
    end
  end
  
  def edit
    @policyname = Policyname.find(params[:id])
  end
  
  def create
    @policyname = Policyname.new(params[:policyname])
    @policyname.created_by = @created_by
    
    respond_to do |format|
      if @policyname.save
        format.html { redirect_to(@policyname, :notice => 'Policy was successfully created.') }
        format.xml  { render :xml => @policyname, :status => :created, :location => @policyname }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @policyname.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def update
    @policyname = Policyname.find(params[:id])
    @policyname.updated_by = @created_by
    
    respond_to do |format|
      if @policyname.update_attributes(params[:policyname])
        format.html { redirect_to(@policyname, :notice => 'Policy was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @policyname.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @policyname = Policyname.find(params[:id])
    @policyname.destroy
    
    respond_to do |format|
      format.html { redirect_to(policynames_url) }
      format.xml  { head :ok }
    end
  end
  private
  def recent_items
    @recent_policynames = Policyname.order('created_at DESC').limit(5)
  end
  
  def sort_column
    Policyname.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/policynames_helper.rb
module PolicynamesHelper
end

app/views/policynames/_form.html.erb
<div class="form-container">
    <%= form_for(@policyname) do |f| %>
    <p class="legend">
        <strong>Note:</strong>
        Required fields are marked with an asterisk (<em>*</em>)
    </p>
    <fieldset>
        <%= f.error_messages %>
        <div>
            <label for="name">
                Name <em>*</em>
            </label>
            <%= f.text_field :name, :id=>"statename", :onChange=>"capitalizeMe(this)",:class => "formTextBox tipTip",:title=>"Enter Policy Name<br/>Ex:DLF Dhana Suraksha" %>
            <script type="text/javascript">
                var statename = new LiveValidation('statename', {
                    onlyOnSubmit: true
                });
                statename.add(Validate.Presence)
            </script>
        </div>
        <div>
            <label for="description ">
                Description 
            </label>
            <%= f.text_area :description ,:cols=>28,:rows=>5,:class=>"tipTip",:title=>"Enter Description of the Policy" %>
        </div>
        <div class="actions">
            <%= f.submit 'Save Policy',:class=>"btnEdit" %>
        </div>
    </fieldset>
    <% end %>
</div>

app/views/policynames/_policynames.html.erb
<div class="list">
  <table width="100%">
    <tr>
      <td align="right">
        <b><i>per page</i></b>
        <%= per_page %> | <%= page_entries_info @policynames %>
      </td>
    </tr>
  </table>
  <table class="tablesorter" cellspacing="1">
    <thead>
    <tr>
      <th><%= t('SNo') %></th>
      <th class="header"><%= sortable 'name' %></th>
      <th><%= t('Description') %></th>
      <th><%= t('Created by') %></th>
      <th>Created On</th>
      <th><%= t('Actions') %></th>
    </tr>
    </thead>
    <% i=1 %>
    <% @policynames.each do |policyname| %>
        <tr>
          <td><%= i %></td>
          <td><%= highlight(policyname.name, params[:search]) %></td>
          <td><%= policyname.description %></td>
          <td><%= @created_name %></td>
          <td><%= policyname.created_at.strftime('%d-%b-%Y') %></td>
          <td><%= link_to t('View'), policyname, :class=>"tipTip2", :title => "View Policy" %>
            <!--<%= link_to t('Edit'), edit_policyname_path(policyname), :class=>"tipTip1", :title => "Edit Policy" %>-->
            <!--<%= link_to 'Delete', policyname, :confirm => 'Do you want really want to delete this policy?', :method => :delete %>--></td>
        </tr>
        <% i = i + 1 %>
    <% end %>
  </table>

  <div class="flickr_pagination">
   <%= page_entries_info @policynames, :entry_name => 'Policy Name' %> <%= will_paginate @policynames, :container => false %>
  </div>
</div>

app/views/policynames/_recent_items.html.erb
<% for policyname in @recent_policynames %>
    <li class="" id="recent_policyname_<%= policyname.id %>">
      <dt>
        <%= link_to truncate(policyname.name, :length=>25), policyname_path(policyname), :class=>"tipTip1", :title => "View Policy Registration" %>
      </dt>
      <tt>
        <br/>
      </tt>
    </li>
<% end %>

app/views/policynames/edit.html.erb
<h3>Policy Names | Edit Policy</h3>

<%= render 'form' %>

<%= link_to 'Show', @policyname, :class=>"more" %> &nbsp;
<%= link_to 'Back', policynames_path,:class=>"more" %>

app/views/policynames/index.html.erb
<h3><%= t('Policy_Names') %> | <%= t('Manage Policy Names') %></h3>
<%= link_to t('New_Policy_Name'), new_policyname_path, :class=>"more tipTip2", :title => "Create New Policy" %> <%= link_to t('Export'), '#', :class=>"more" %>
<br/>

<div class="list">
  <table width="100%">
    <tr>
      <td align="right">
        <b><i>per page</i></b>
        <%= per_page %> | <%= page_entries_info @policynames %>
      </td>
    </tr>
  </table>
  <table class="tablesorter" cellspacing="1">
    <thead>
    <tr>
      <th><%= t('SNo') %></th>
      <th class="header"><%= sortable 'name' %></th>
      <th><%= t('Description') %></th>
      <th><%= t('Created by') %></th>
      <th>Created On</th>
      <th><%= t('Actions') %></th>
    </tr>
    </thead>
    <% i=1 %>
    <% @policynames.each do |policyname| %>
        <tr>
          <td><%= i %></td>
          <td><%= highlight(policyname.name, params[:search]) %></td>
          <td><%= policyname.description %></td>
          <td><%= @created_name %></td>
          <td><%= policyname.created_at.strftime('%d-%b-%Y') %></td>
          <td><%= link_to t('View'), policyname, :class=>"tipTip2", :title => "View Policy" %>
            <!--<%= link_to t('Edit'), edit_policyname_path(policyname), :class=>"tipTip1", :title => "Edit Policy" %>-->
            <!--<%= link_to 'Delete', policyname, :confirm => 'Do you want really want to delete this policy?', :method => :delete %>--></td>
        </tr>
        <% i = i + 1 %>
    <% end %>
  </table>

  <div class="flickr_pagination">
   <%= page_entries_info @policynames, :entry_name => 'Policy Name' %> <%= will_paginate @policynames, :container => false %>
  </div>
</div>

app/views/policynames/index.js.erb
$("#policynames").html("<%= escape_javascript(render 'policynames' ) %>");

app/views/policynames/new.html.erb
<h3>Policy Names | New Policy Creation</h3>
<div class="list">
  <div class="help_text">
    * Fill the below form for New Policy Registration.<br/>* Please check all entries before Save.
  </div>
<%= render 'form' %>
<%= link_to 'Back to Policy Registrations', policynames_path, :class=>'more tipTip1',:title => "Back to Policy Registrations" %>
</div>

app/views/policynames/show.html.erb
<h3>Policy Names | View Policy Details</h3>
<div class="formbox">
<div class="desc">Name : <%= @policyname.name %></div>
<div class="divider"></div>
<div class="desc">Description : <%= @policyname.description %> </div>
<div class="divider"></div>
<div class="desc">Created By : <%= User.find(@policyname.created_by).name %> </div>
<div class="divider"></div>
<div class="desc">Created At : <%= @policyname.created_at.strftime('%d-%b-%Y') %> </div>
<div class="divider"></div>
</div>

<br />
<%= link_to 'Edit', edit_policyname_path(@policyname),:class=>"more" %> &nbsp;
<%= link_to 'Back', policynames_path,:class=>"more" %>