config/routes.rb
Csc::Application.routes.draw do
  resources :shortmessages do
    get :export, :on=>:collection
  end

  resources :universities

  resources :deducations do
    get :payment_mode, :on=>:collection
    get :get_amount, :on=>:collection
    get :update_status, :on=>:member
    get :print, :on=>:member
  end

  resources :courses

  resources :downloads

  resources :bulkmails do
    get :mail_mode, :on=>:collection
  end

  resources :deposits do
    get :transaction_mode, :on=>:collection
    get :update_status, :on=>:member
    get :update_funds, :on=>:member
    get :upload_funds, :on=>:collection
    get :upload, :on=>:member
    put :fund_save, :on=>:collection
    get :suspense_transactions, :on=>:collection
  end

  resources :pancards do
    get :update_status, :on=>:member
    get :payment_mode, :on=>:collection
    get :print, :on=>:member
    get :suspense_transactions, :on=>:collection
  end

  resources :tickets

  resources :policynames

  resources :insurances do
    get 'export', :on=>:collection
    get 'print', :on=>:member
    get 'receipt', :on=>:member
    get 'courier', :on=>:member
    post 'courier_update', :on=>:member
    get 'verifyinsurance', :on=>:collection
    get 'update_status', :on=>:member
    get 'verifiedinsurance', :on=>:collection
    get 'renewpolicy', :on=>:collection
    put 'createrenew', :on=>:collection
    get :eodreport, :on=>:collection
    get :daterangereport, :on=>:collection
    get :eodexport, :on=>:collection
    get :daterangeexport, :on=>:collection
    get :payment_mode, :on=>:collection
    get :suspense_transactions, :on=>:collection
  end

  resources :user_profiles

  resources :blocks do
    get 'load_districts', :on => :collection
    get :export, :on=>:collection
  end

  resources :divisions do
    get :export, :on=>:collection
  end

  resources :districts do
    get :export, :on => :collection
  end

  resources :states do
    get :export, :on=>:collection
  end

  resources :users do
    get 'verifyuser', :on=>:collection
    get 'update_status', :on=>:member
    get 'profile', :on=>:member
    get 'document', :on=>:member
    put 'upload_document', :on=>:member
    get 'editprofile', :on=>:member
    put 'updateprofile', :on=>:member
    get 'upload', :on=>:collection
    post 'csv_import', :on=>:collection
    get 'changepassword', :on=>:member
    get :resetpass, :on=>:member
    get :payment_mode, :on=>:collection
    get :activity, :on=>:member
    get :export, :on=>:collection
  end

  resources :roles

  resources :user_sessions

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"

  match "user_info/:id" => "user_info#index", :as=>:user_info
  get "user_info/index"


  match ':controller(/:action(/:id(.:format)))'
end

app/models/insurance.rb
#Author: Chaitanya
#Date: June 5th 2011
#====================================
class Insurance < ActiveRecord::Base
  
  #Relations
  belongs_to :district
  belongs_to :state
  belongs_to :policyname
  belongs_to :user

  #validations
  #validates_uniqueness_of :application_number


  #Insurance Type stored in DB
  INSURANCE_TYPES = [
  [ "New Policy" , "New" ],
  [ "Renewal Policy" , "Renewal" ]
  ]
  
  #Payment Frequency Stored in DB
  PAYMENT_FREQUENY = [
  [ "Annual" , "Annual" ],
  [ "Semi Annual" , "Semi Annual" ],
  [ "Quarterly" , "Quarterly" ],
  [ "Monthly", "Monthly"]
  ]
  
  # AGE = Array.new(8) {|i| 1920+i}
  #search using meta_where Gem
  def self.search(search)
    if search
      where({:transaction_id.matches => "%#{search}%"} | {:transaction_date.matches => "%#{search}%"}  )
    else
      scoped
    end
  end
  
end

app/controllers/insurances_controller.rb
#Author: Chaitanya
#Date: June 04 2011
#========================================
class InsurancesController < ApplicationController
  layout "admin"
  before_filter :require_user, :recent_items
  filter_access_to :all
  helper_method :sort_column, :sort_direction
######## For SMS Gateway ##############
  require 'net/http'
  require 'uri'
####################################
  def index
    @insurances = Insurance.where(:created_by=>current_user.id,:suspense_status => false).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page, :per_page=>per_page) if has_role?(:vle) or has_role?(:dlf_agent)
    @insurances = Insurance.where(:suspense_status => false).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page, :per_page=>per_page) if has_role?(:admin)
    @insurances = Insurance.where(:suspense_status => false).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page, :per_page=>per_page) if has_role?(:manager)
    @insurances = Insurance.joins({:user=>:user_profile}).where({:user=>{:user_profile=>{:district_id=>current_user.user_profile.district_id}}},:suspense_status=>false).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page, :per_page=>per_page) if has_role?(:district_manager) or has_role?(:district_engineer)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @insurances }
      format.js
    end
  end

  def show
    @insurance = Insurance.find(params[:id])
    render :layout => "application"
  end

  def new
    @insurance = Insurance.new
    render :layout => "application"
  end

  def edit
    @insurance = Insurance.find(params[:id])
  end

  def create
    @insurance = Insurance.new(params[:insurance])
    @insurance.created_by = @insurance.user_id = current_user.id

    @insurance.transaction_id = 'INSU/' + current_user.id.to_s + '/' + Time.now.strftime('%y%m%d%H%M%S').to_s

    @user_profile_user = UserProfile.find(:first, :conditions=>{:user_id=>current_user.id})
    user_profile_user_funds = @user_profile_user.available_funds

    if user_profile_user_funds <=0
      flash[:error] = "Sorry! You have No Funds to perform Transaction."
      redirect_to(insurances_url)
    else
      user_profile_remaining_funds = user_profile_user_funds - params[:insurance][:collected_premium].to_f #transaction_records_sum

      if user_profile_remaining_funds < 0
        flash[:error] = "Sorry! You have Insufficient Funds.Transaction is Cancelled."
        redirect_to(insurances_url)
      else
        respond_to do |format|
          if @insurance.save
            @insurance_transaction = Transaction.new(:user_id=>current_user.id, :transaction_number=>@insurance.transaction_id, :transaction_date=>Date.today, :transaction_mode=>'Dr', :service=>"Insurance", :amount=>params[:insurance][:collected_premium])
            @insurance_transaction.save
            @user_profile_user.available_funds = user_profile_remaining_funds
            @user_profile_user.save

            sms_status ### Send SMS

            format.html { redirect_to(@insurance, :notice => 'Insurance was successfully created.') }
            format.xml { render :xml => @insurance, :status => :created, :location => @insurance }
          else
            format.html { render :action => "new" }
            format.xml { render :xml => @insurance.errors, :status => :unprocessable_entity }
          end
        end
      end
    end

  end

  def update
    @insurance = Insurance.find(params[:id])
    @insurance.updated_by = @created_by

    respond_to do |format|
      if @insurance.update_attributes(params[:insurance])
        format.html { redirect_to(@insurance, :notice => 'Insurance was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @insurance.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @insurance = Insurance.find(params[:id])
    @insurance.destroy

    respond_to do |format|
      format.html { redirect_to(insurances_url) }
      format.xml { head :ok }
    end
  end

  def print
    @insurance = Insurance.find(params[:id])

    #conten for QR Code
    @qrcode = @insurance.transaction_id + ',' + @insurance.transaction_date.strftime('%d-%m-%Y') + ',' + @insurance.collected_premium.to_s + ',' + UserProfile.find_by_user_id(@insurance.user_id).vle_code + ',' + UserProfile.find_by_user_id(@insurance.user_id).panchayat + '/' + UserProfile.find_by_user_id(@insurance.user_id).district.name + ',' + UserProfile.find_by_user_id(@insurance.user_id).district_id.to_s + UserProfile.find_by_user_id(@insurance.user_id).state_id.to_s + @insurance.user_id.to_s + UserProfile.find_by_user_id(@insurance.user_id).id.to_s

    #PDF Render
    html = render_to_string :layout => false
    kit = PDFKit.new(html)
    kit.stylesheets << RAILS_ROOT + '/public/stylesheets/styles.css'
    send_data(kit.to_pdf, :filename => "Insurance Verified Receipt-#{@insurance.transaction_id}_Verified.pdf", :type => 'application/pdf')
  end

  def receipt
    @insurance = Insurance.find(params[:id])

    #conten for QR Code
    @qrcode = @insurance.transaction_id + ',' + @insurance.transaction_date.strftime('%d-%m-%Y') + ',' + @insurance.collected_premium.to_s + ',' + UserProfile.find_by_user_id(@insurance.user_id).vle_code + ',' + UserProfile.find_by_user_id(@insurance.user_id).panchayat + '/' + UserProfile.find_by_user_id(@insurance.user_id).district.name + ',' + UserProfile.find_by_user_id(@insurance.user_id).district_id.to_s + UserProfile.find_by_user_id(@insurance.user_id).state_id.to_s + @insurance.user_id.to_s + UserProfile.find_by_user_id(@insurance.user_id).id.to_s

    #PDF Render
    html = render_to_string :layout => false
    kit = PDFKit.new(html)
    kit.stylesheets << RAILS_ROOT + '/public/stylesheets/styles.css'
    send_data(kit.to_pdf, :filename => "Insurance Receipt-#{@insurance.transaction_id}.pdf", :type => 'application/pdf')
  end

  def courier
    @insurance = Insurance.find(params[:id])
    render :layout => "application"
  end

  def courier_update
    @insurance = Insurance.find(params[:id])
    @insurance.awb_number = params[:insurance][:awb_number]
    @insurance.physical_date = params[:insurance][:physical_date]
    @insurance.courier = params[:insurance][:courier]

    if  @insurance.save
      flash[:success] = "Courier Details Updated."
      redirect_to(insurances_url)
    else
      render 'courier', :id=>params[:id]
    end
  end

  def verifyinsurance
    @insurances = Insurance.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page, :per_page=>per_page)
  end

  def update_status
    insurance = Insurance.find(params[:id])
    insurance.update_attribute('status', insurance.status ? false : true)
    flash[:success] = "Insurance Transaction Status has been updated."
    respond_to do |format|
      format.html { redirect_to(:controller=>'insurances', :action=>'index') }
    end
  end

  def renewpolicy
    @insurance = Insurance.new
    render :layout => "application"
  end

  def createrenew
    @insurance = Insurance.new(params[:insurance])
    @insurance.created_by = @insurance.user_id = current_user.id

    @insurance.transaction_id = 'INSU/' + current_user.id.to_s + '/' + Time.now.strftime('%y%m%d%H%M%S').to_s

    # puts @insurance.instrument_date= params[:insurance][:instrument_date]

    @user_profile_user = UserProfile.find(:first, :conditions=>{:user_id=>current_user.id})
    user_profile_user_funds = @user_profile_user.available_funds

    if user_profile_user_funds <=0
      flash[:error] = "Sorry! You have No Funds to perform Transaction.Please deposit Funds to continue the Transactions"
      redirect_to(insurances_url)
    else
      user_profile_remaining_funds = user_profile_user_funds - params[:insurance][:collected_premium].to_f #transaction_records_sum

      if user_profile_remaining_funds < 0
        flash[:error] = "Sorry! You have Insufficient Funds.Transaction is Cancelled. Please deposit Funds to continue the Transactions"
        redirect_to(insurances_url)
      else
        respond_to do |format|
          if @insurance.save
            @insurance_transaction = Transaction.new(:user_id=>current_user.id, :transaction_number=>@insurance.transaction_id, :transaction_date=>Date.today, :transaction_mode=>'Dr', :service=>"Insurance", :amount=>params[:insurance][:collected_premium])
            @insurance_transaction.save
            @user_profile_user.available_funds = user_profile_remaining_funds
            @user_profile_user.save

            sms_status # sent SMS

            format.html { redirect_to(@insurance, :notice => 'Insurance was successfully created.') }
            format.xml { render :xml => @insurance, :status => :created, :location => @insurance }
          else
            format.html { render :action => "new" }
            format.xml { render :xml => @insurance.errors, :status => :unprocessable_entity }
          end
        end
      end
    end
  end

  def payment_mode
    respond_to do |format|
      format.js
    end
  end

  def sms_status
    mobile = @insurance.mobile
    #name = @pancard.first_name + @pancard.last_name
    #message = "Dear+Customer,+A Premium+of+Rs."+@insurance.collected_premium.to_s+"/-+received+towards+"+@insurance.policyname.name+"+Policy.+Your+Reference+No:+"+@insurance.transaction_id+"."
    if @insurance.policy_type == "New"
      message = "Dear Customer, A Premium of Rs." + @insurance.collected_premium.to_s + "/- received towards New "+ @insurance.policyname.name + "Policy. Your Reference No:"+ @insurance.transaction_id + "."
    else

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/views/insurances/_recent_items.html.erb
<% for insurance in  @recent_insurances %>
<li class="" id="recent_insurance_<%= insurance.id%>">
    <dt>
        <%=link_to truncate(insurance.transaction_id,:length=>27),insurance_path(insurance), :class=>"tipTip1", :title=>"View Transaction" %>
    </dt>
    <tt>
        <br/>
    </tt>
</li>
<% end %>

app/views/insurances/courier.html.erb
<h3>Insurances | Update Insurance Courier Details</h3>
<%= render :partial=>'common/funds' %>
<br/><br/>
<div class="list">
  <div class="help_text">
    * Fill the below form for Courier Entry.<br/>* Please check all entries before Save.
  </div>
<div class="form-container">
  <%= form_for(:insurance,@insurance,:url=>{:action=>'courier_update',:id=>@insurance.id}) do |f| %>
      <p class="legend">
        <strong>Note:</strong>
        Required fields are marked with an asterisk (
        <em>*</em>)
      </p>
      <fieldset>
        <%= f.error_messages %>
        <div>
          <label for="application_number">
            AWB (Air Way Bill) Number:
            <em>*</em>
          </label>
          <%= f.text_field :awb_number,:id=>"awbnumber",:class => "tipTip", :title=>"Air Way Bill Number. Ex:2585896", :size=>20  %>
          <script type="text/javascript">var awbnumber = new LiveValidation('awbnumber');
          awbnumber.add(Validate.Presence)</script>
        </div>
        <div>
          <label for="address1">
            Date of Dispatch:<em>*</em>
          </label>
          <%= text_field_tag 'insurance[physical_date]', '', :class => "formTextBox", :id=>'physical_date' %>
          <script type="text/javascript">var physical_date = new LiveValidation('physical_date');
          physical_date.add(Validate.Presence)</script>
        </div>
        <div>
          <label for="application_number">
            Courier Name: <em>*</em>
          </label>
          <%= f.text_field :courier,:id=>"courier", :class => "tipTip", :title=>"Courier Name. Ex:BlueDart", :size=>20 %>
          <script type="text/javascript">var courier = new LiveValidation('courier');
          courier.add(Validate.Presence)</script>
        </div>
        <div class="actions">
          <%= f.submit "Save Courier Details",:class=>'btnEdit' %>
        </div>
      </fieldset>
  <% end %>
</div>
<script>
    $(function() {
        $("#physical_date").datepicker({dateFormat:'dd-mm-yy', maxDate:0,changeMonth: true,changeYear: true,currentText: 'Now' });
    });
</script>
<%= link_to 'Back to Insurance', insurances_path, :class=>"more tipTip1",:title => "Back to Insurance" %>
</div>

app/views/insurances/daterangereport.html.erb
<h3>Insurances | Date Range Report</h3>
<% if has_role?(:vle)%>
<%= link_to 'New Insurance', new_insurance_path, :class=>"more" %>&nbsp;<%= link_to 'Renew Insurance', {:action=>'renewpolicy'}, :class=>"more" %>&nbsp;
<br/>
<div class="inline">
<div align="right" style="float: right;" class="inline">Available Balance:</div>
</div>
<%end%>
<% if has_role?(:admin)%>
<%= link_to 'Export Date Report', {:action=>'daterangeexport', :start_date=> @start_date? @start_date:'', :end_date => @end_date? @end_date:'' } , :class=>"more" %>
<%= link_to 'EOD Report', {:action=>'eodreport'},:class=>'more'%>
<%= link_to 'Report Home', insurances_path,:class=>'more'%>
<%end%>
<br/>
<br/>

        <%= form_tag  do -%>
          Start Date : <%= text_field_tag 'start_date',  @start_date? @start_date:'' %>
          End Date : <%= text_field_tag 'end_date', @end_date? @end_date:'' %>
          <%= submit_tag 'Get' %>
        <% end -%>
<div class="list">
	<% if @insurances.blank? %>
	Please select valide date range
	<% else %>
    <table width="100%">
        <tr>
            <td align="right">
                <b><i>per page</i></b>
                <%=per_page %>| <%= page_entries_info @insurances %>
            </td>
        </tr>
    </table>
    <table class="tablesorter" cellspacing="1">
        <thead>
            <tr>
                <th>
                    SNo
                </th>
				<th>
                    Status
                </th>
                <th class="header">
                    <%= sortable 'transaction_id',"Transaction No" %>
                </th>
                <th>
                    Transaction Date
                </th>
                <th>
                    Type
                </th>
                <th>
                    Policy Name
                </th>
                <th>
                    Insured Name
                </th>
                <th>
                    Sum Assured
                </th>
                <th>
                    Created On
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            <% i=1 %>
            <% @insurances.each do |insurance| %>
            <tr>
                <td>
                    <%= i %>
                </td>
               <td>
                    <% if insurance.status == false %>
						<font color='red'><b>P</b></font>
					<%else%>
						<font color='green'><b>A</b></font>
					<%end%>
                </td>

                <td>
                    <%= highlight(insurance.transaction_id,params[:search]) %>
                </td>
                <td>
                    <%= insurance.transaction_date.strftime('%d-%m-%Y') %>
                </td>
                <td>
                    <%= insurance.policy_type %>
                </td>
                <td>
                    <%= insurance.policyname.name %>
                </td>
                <td>
                    <%= insurance.insured_holder %>
                </td>
                <td>
                    <%= insurance.sum_assured %>
                </td>
                <td>
                    <%= insurance.created_at.strftime('%d-%m-%Y') %>
                </td>
                <td>
                    <%= link_to 'View', insurance %> 
					<% if has_role?(:vle)%>
					| 
					<%= link_to 'Courier Entry', {:action=>'courier', :id=>insurance.id} %> | 
					<!-- <%= link_to 'Print Receipt', {:action=>'print',:id=>insurance.id} %> -->
					<%= link_to 'Receipt', {:action=>'receipt', :id=>insurance.id} %>
					<%end%>
                </td>
            </tr>
            <% i =  i + 1 %>
            <% end %>
        </tbody>
    </table>
    <div class="flickr_pagination">
        <%= will_paginate @insurances, :container => false %>
    </div>
	<% end %>
</div>
       <script>
	          $(function() {
		          $( "#start_date" ).datepicker({dateFormat:'dd-mm-yy', maxDate:0 });
		          $( "#end_date" ).datepicker({dateFormat:'dd-mm-yy', maxDate:0 });
	          });
      	</script>

app/views/insurances/eodreport.html.erb
<h3>Insurances | End Of the Day Report</h3>
<% if has_role?(:admin)%>
<%= link_to 'Export EOD Report', {:action=>'eodexport'}, :class=>"more" %>
<%= link_to 'Date Range Report', {:action=>'daterangereport'},:class=>'more'%>
<%= link_to 'Report Home', insurances_path, :class=>'more'%>
<%end%>

<div class="list">
    <table width="100%">
        <tr>
            <td align="right">
                <b><i>per page</i></b>
                <%=per_page %>| <%= page_entries_info @insurances %>
            </td>
        </tr>
    </table>
    <table class="tablesorter" cellspacing="1">
        <thead>
            <tr>
                <th>
                    SNo
                </th>
				<th>
                    Status
                </th>
                <th class="header">
                    <%= sortable 'transaction_id',"Transaction No" %>
                </th>
                <th>
                    Transaction Date
                </th>
                <th>
                    Type
                </th>
                <th>
                    Policy Name
                </th>
                <th>
                    Insured Name
                </th>
                <th>
                    Sum Assured
                </th>
                <th>
                    Created On
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            <% i=1 %>
            <% @insurances.each do |insurance| %>
            <tr>
                <td>
                    <%= i %>
                </td>
               <td>
                    <% if insurance.status == false %>
						<font color='red'><b>P</b></font>
					<%else%>
						<font color='green'><b>A</b></font>
					<%end%>
                </td>

                <td>
                    <%= highlight(insurance.transaction_id,params[:search]) %>
                </td>
                <td>
                    <%= insurance.transaction_date.strftime('%d-%m-%Y') %>
                </td>
                <td>
                    <%= insurance.policy_type %>
                </td>
                <td>
                    <%= insurance.policyname.name %>
                </td>
                <td>
                    <%= insurance.insured_holder %>
                </td>
                <td>
                    <%= insurance.sum_assured %>
                </td>
                <td>
                    <%= insurance.created_at.strftime('%d-%m-%Y') %>
                </td>
                <td>
                    <%= link_to 'View', insurance %> 
					<% if has_role?(:vle)%>
					| 
					<%= link_to 'Courier Entry', {:action=>'courier', :id=>insurance.id} %> | 
					<!-- <%= link_to 'Print Receipt', {:action=>'print',:id=>insurance.id} %> -->
					<%= link_to 'Receipt', {:action=>'receipt', :id=>insurance.id} %>
					<%end%>
                </td>
            </tr>
            <% i =  i + 1 %>
            <% end %>
        </tbody>
    </table>
    <div class="flickr_pagination">
        <%= will_paginate @insurances, :container => false %>
    </div>
</div>

app/views/insurances/index.js.erb
$("#insurances").html("<%= escape_javascript(render 'insurances' ) %>");

app/views/insurances/new.html.erb
<h3>Insurances | New Insurance Policy Registration (नई बीमा पॉलिसी पंजीकरण)</h3>
<%= render :partial=>'common/funds' %>
<br/><br/>
<div class="list">
  <div class="help_text">
    * Fill the below form for New Insurance Policy.(नई बीमा पॉलिसी के लिए नीचे दिए गए फार्म भरें)<br/>
    * Please check all entries before Save (सहेजें से पहले सभी प्रविष्टियों की जाँच करें).
    <br/>*<font color="blue"> FURTHER MODIFICATION WILL NOT POSSIBLE AFTER SUBMITTING THE FORM (फार्म जमा करने के बाद आगे कोई संशोधन संभव नहीं होगा).</font>
  </div>
  <%= render 'form' %>
  <%= link_to 'Back to Insurance', insurances_path, :class=>"more tipTip1", :title => "Back to Insurance" %>
</div>

app/views/insurances/payment_mode.js.erb
<% if params[:name].eql?('Cash')%>
$('#transaction_fields').html("");
<% else %>
$('#transaction_fields').html("<%=escape_javascript(render 'mode')%>");
<% end %>

app/views/insurances/verifiedinsurance.html.erb
<h3>Insurances | Manage Insurances</h3>
<%= link_to 'New Insurance', new_insurance_path, :class=>"more" %>
<br/>
<div class="list">
    <table width="100%">
        <tr>
            <td align="right">
                <b><i>per page</i></b>
                <%=per_page %>| <%= page_entries_info @insurances %>
            </td>
        </tr>
    </table>
    <table class="tablesorter" cellspacing="1">
        <thead>
            <tr>
                <th>
                    SNo
                </th>
				<th>
                    Status
                </th>
                <th class="header">
                    <%= sortable 'transaction_id' %>
                </th>
                <th>
                    Transaction Date
                </th>
                <th>
                    Type
                </th>
                <th>
                    Policy Name
                </th>
                <th>
                    Insured Name
                </th>
                <th>
                    Sum Assured
                </th>
                <th>
                    Created On
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            <% i=1 %>
            <% @insurances.each do |insurance| %>
            <tr>
                <td>
                    <%= i %>
                </td>
               <td>
                    <% if insurance.status == false %>
						<font color='red'><b>P</b></font>
					<%else%>
						<font color='green'><b>A</b></font>
					<%end%>
                </td>

                <td>
                    <%= highlight(insurance.transaction_id,params[:search]) %>
                </td>
                <td>
                    <%= insurance.transaction_date.strftime('%d-%m-%Y') %>
                </td>
                <td>
                    <%= insurance.policy_type %>
                </td>
                <td>
                    <%= insurance.policyname.name %>
                </td>
                <td>
                    <%= insurance.insured_holder %>
                </td>
                <td>
                    <%= insurance.sum_assured %>
                </td>
                <td>
                    <%= insurance.created_at.strftime('%d-%m-%Y') %>
                </td>
                <td>
                    <%= link_to 'View', insurance %> | 
					<%= link_to 'Print Receipt', {:action=>'print',:id=>insurance.id} %>
                </td >
            </tr>
            <% i =  i + 1 %>
            <% end %>
        </tbody>
    </table>
    <div class="flickr_pagination">
        <%= will_paginate @insurances, :container => false %>
    </div>
</div>