config/routes.rb
Csc::Application.routes.draw do
  resources :shortmessages do
    get :export, :on=>:collection
  end

  resources :universities

  resources :deducations do
    get :payment_mode, :on=>:collection
    get :get_amount, :on=>:collection
    get :update_status, :on=>:member
    get :print, :on=>:member
  end

  resources :courses

  resources :downloads

  resources :bulkmails do
    get :mail_mode, :on=>:collection
  end

  resources :deposits do
    get :transaction_mode, :on=>:collection
    get :update_status, :on=>:member
    get :update_funds, :on=>:member
    get :upload_funds, :on=>:collection
    get :upload, :on=>:member
    put :fund_save, :on=>:collection
    get :suspense_transactions, :on=>:collection
  end

  resources :pancards do
    get :update_status, :on=>:member
    get :payment_mode, :on=>:collection
    get :print, :on=>:member
    get :suspense_transactions, :on=>:collection
  end

  resources :tickets

  resources :policynames

  resources :insurances do
    get 'export', :on=>:collection
    get 'print', :on=>:member
    get 'receipt', :on=>:member
    get 'courier', :on=>:member
    post 'courier_update', :on=>:member
    get 'verifyinsurance', :on=>:collection
    get 'update_status', :on=>:member
    get 'verifiedinsurance', :on=>:collection
    get 'renewpolicy', :on=>:collection
    put 'createrenew', :on=>:collection
    get :eodreport, :on=>:collection
    get :daterangereport, :on=>:collection
    get :eodexport, :on=>:collection
    get :daterangeexport, :on=>:collection
    get :payment_mode, :on=>:collection
    get :suspense_transactions, :on=>:collection
  end

  resources :user_profiles

  resources :blocks do
    get 'load_districts', :on => :collection
    get :export, :on=>:collection
  end

  resources :divisions do
    get :export, :on=>:collection
  end

  resources :districts do
    get :export, :on => :collection
  end

  resources :states do
    get :export, :on=>:collection
  end

  resources :users do
    get 'verifyuser', :on=>:collection
    get 'update_status', :on=>:member
    get 'profile', :on=>:member
    get 'document', :on=>:member
    put 'upload_document', :on=>:member
    get 'editprofile', :on=>:member
    put 'updateprofile', :on=>:member
    get 'upload', :on=>:collection
    post 'csv_import', :on=>:collection
    get 'changepassword', :on=>:member
    get :resetpass, :on=>:member
    get :payment_mode, :on=>:collection
    get :activity, :on=>:member
    get :export, :on=>:collection
  end

  resources :roles

  resources :user_sessions

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"

  match "user_info/:id" => "user_info#index", :as=>:user_info
  get "user_info/index"


  match ':controller(/:action(/:id(.:format)))'
end

app/models/state.rb
#Author: Chaitanya 
#
#==================================
class State < ActiveRecord::Base
  #Relations
  has_many :divisions,:dependent=>:destroy
  has_many :districts,:dependent=>:destroy
  has_many :blocks,:dependent=>:destroy
  
  #Validations
  validates :name, :presence => true, :uniqueness => true, :length => { :maximum => 100}

  #search using meta_where Gem
  def self.search(search)
    if search
      where(:name.matches => "%#{search}%")
    else
      scoped
    end
  end

end

app/controllers/states_controller.rb
#Created :chaitanya
#date: 25 May 2011
#====================================
class StatesController < ApplicationController
  layout "admin"
  before_filter :require_user, :recent_items
  filter_access_to :all
  helper_method :sort_column, :sort_direction

  def index
    @states = State.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page, :per_page=>per_page)
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @states }
      format.js
    end
  end

  def show
    @state = State.find(params[:id])
    render :layout => "application"

  end

  def new
    @state = State.new
    render :layout => "application"
  end

  def edit
    @state = State.find(params[:id])
    render :layout => "application"
  end

  def create
    @state = State.new(params[:state])
    @state.created_by = @created_by
    respond_to do |format|
      if @state.save
        format.html { redirect_to(@state, :notice => 'State was successfully created.') }
        format.xml { render :xml => @state, :status => :created, :location => @state }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @state.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @state = State.find(params[:id])
    @state.updated_by = @created_by
    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to(@state, :notice => 'State was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @state.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to(states_url) }
      format.xml { head :ok }
    end
  end
  def export
    @states = State.all
    html = render_to_string :layout => false
    kit  = PDFKit.new(html,:page_size => 'Legal')
 #       kit.stylesheets << RAILS_ROOT + '/public/stylesheets/style.css'
    send_data(kit.to_pdf, :filename => "States.pdf", :type => 'application/pdf')

  end
##################################################################################################################
  private
  def recent_items
    @recent_states = State.order('created_at DESC').limit(5)
  end

  def sort_column
    State.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
##################################################################################################################
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<div class="form-container">
    <%= form_for(@state) do |f| %>
    <p class="legend">
        <strong>Note:</strong>
        Required fields are marked with an asterisk (<em>*</em>)
    </p>
    <fieldset>
        <%= f.error_messages %>
        <div>
            <label for="name">
                Name <em>*</em>
            </label>
            <%= f.text_field :name, :id=>"statename", :onChange=>"capitalizeMe(this)",:class => "formTextBox tipTip",:title=>"Enter Name of the State" %>
            <script type="text/javascript">
                var statename = new LiveValidation('statename', {
                    onlyOnSubmit: true
                });
                statename.add(Validate.Presence)
            </script>
        </div>
      <div>
          <label for="name">
              Short Name <em>*</em>
          </label>
          <%= f.text_field :short_code, :id=>"shortname", :class => "formTextBox tipTip",:title=>"Enter Short Name for State <br/>Ex: BR" %> (Ex: BR- Bihar)
          <script type="text/javascript">
              var shortname = new LiveValidation('shortname', {
                  onlyOnSubmit: true
              });
              shortname.add(Validate.Presence)
          </script>
      </div>

        <div>
            <label for="description ">
                Description 
            </label>
            <%= f.text_area :description ,:cols=>28,:rows=>5,:class=>"tipTip",:title=>"Enter Description"%>
        </div>
        <div class="actions">
            <%= f.submit :class=>"btnEdit" %>
        </div>
    </fieldset>
    <% end %>
</div>

app/views/states/_recent_items.html.erb
<% for state in  @recent_states %>
<li class="" id="recent_state_<%= state.id%>">
    <dt>
        <%=link_to truncate(state.name,:length=>27),state_path(state),:class => "tipTip1",:title => "View State Details" %>
    </dt>
    <tt>
        <br/>
    </tt>
</li>
<% end %>

app/views/states/_states.html.erb
<div class="help_text">
  * List of All States.<br/>
</div>
  <div class="list">
      <table width="100%">
          <tr>
              <td align="right">
              <b>
              <i>per page</i>
              </b>
              <%= per_page %> | <%= page_entries_info @states,:entry_name => 'State' %>
              </td>
          </tr>
      </table>
      <table class="tablesorter" cellspacing="1">
          <thead>
              <tr>
                  <th>SNo</th>
                  <th class="header"><%= sortable 'name'%></th>
                  <th>Short Name</th>
                  <th>Description</th>
                  <th>Created By</th>
                  <th>Created On</th>
                  <th>Actions</th>
              </tr>
          </thead>
          <% i=1%>
          <% @states.each do |state| %>
          <tr>
              <td><%= i%></td>
              <td><%= highlight(state.name,params[:search]) %></td>
              <td><%=state.short_code %></td>
              <td><%= state.description %></td>
              <td><%= @created_name %></td>
              <td><%= state.created_at.strftime('%d-%b-%Y')%></td>
              <td><%= link_to 'View', state, :class => "tipTip2",:title => "View State Details" %> |
              <%= link_to 'Edit', edit_state_path(state),:class => "tipTip2",:title => "Edit State Details" %>
              </td>
          </tr>
          <% i =  i + 1%>
          <% end %>
      </table>
      <div class="flickr_pagination1">
       <%= page_entries_info @states, :entry_name => 'State' %>   <%= will_paginate @states, :container => false %>
      </div>
  </div>

app/views/states/edit.html.erb
<h3>States | Edit State</h3>
<div class="list">
  <div class="help_text">
    * Edit the below form for State.<br/>* Please check all entries before Save.
  </div>
<%= render 'form' %>
<%= link_to 'Show', @state, :class=>"more tipTip2",:title => "Show State Details" %> &nbsp;
<%= link_to 'Back to States', states_path,:class=>"more tipTip1",:title => "Back to States" %>
</div>

app/views/states/export.html.erb
<style type="text/css">
    .tablesorter {
        border-collapse: collapse;
        border: 1px solid #cdcdcd;
        font-size: 10px;
        width: 100%;
        text-align: left;
    }

    .tablesorter td, .tablesorter th {
        border-collapse: collapse;
        border: 1px solid #cdcdcd;
    }

    .tablesorter thead tr, .tablesorter thead tr, .tablesorter tfoot tr {
        border: 1px solid #fff;
        font-size: 11px;
        height: 25px;
        padding: 4px;
    }

    .tablesorter tbody td {
        height: 25px;
        padding: 4px;
        vertical-align: middle;
    }
</style>
<h3 align="center">States Report </h3>
<br/>
<table class="tablesorter">
    <thead>
        <tr>
            <th>Name</th>
            <th>Short Name</th>
            <th>Description</th>
        </tr>
    </thead>
    <% @states.each do |state| %>
    <tr>
        <td><%= state.name %></td>
        <td><%=state.short_code %></td>
        <td><%= state.description %></td>
    </tr>
    <% end %>
</table>

app/views/states/index.html.erb
<h3>States | Manage States</h3>

	<%= link_to 'New State', new_state_path, :class=>'more tipTip2',:title => "Create New State" %>&nbsp;
	<%= link_to 'Export',{:action => "export"},:class=>'more tipTip1',:title => "Export all States as PDF file" %>
	<br/> <br/>


<div id="states">
  <%= render 'states' %>
</div>

app/views/states/index.js.erb
$("#states").html("<%= escape_javascript(render 'states' ) %>");

app/views/states/new.html.erb
<h3>States | New State Creation</h3>
<div class="list">
  <div class="help_text">
    * Fill the below form for State.<br/>* Please check all entries before Save.
  </div>
  <%= render 'form' %>
  <%= link_to 'Back to States', states_path, :class=>'more tipTip1',:title => "Back to States" %>
</div>

app/views/states/show.html.erb
<h3>States | View State Details</h3>
<div class="formbox">
<div class="desc">Name : <%= @state.name %></div>
<div class="divider"></div>
<div class="desc">Short Name : <%= @state.short_code %></div>
<div class="divider"></div>
<div class="desc">Description : <%= @state.description %> </div>
<div class="divider"></div>
<div class="desc">Created By : <%= User.find(@state.created_by).name %> </div>
<div class="divider"></div>
<div class="desc">Created At : <%= @state.created_at.strftime('%d-%m-%Y') %> </div>
<div class="divider"></div>
</div>
<div class="bottom_links" >
<%= link_to 'Edit', edit_state_path(@state),:class=>"more tipTip2",:title => "Edit State Details" %> &nbsp;
<%= link_to 'Back', states_path,:class=>"more tipTip1",:title => "Back to States" %>
</div>